server:
  port: 18110
spring:
  application:
    name: file-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:192.168.2.128:8848}
        ip: ${SERVICE_IP:192.168.2.173}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
minio:
  endpoint: ${MINIO_ENDPOINT:http://192.168.2.128:9000}
  access-key: ${MINIO_ACCESS_KEY:trade}
  secret-key: ${MINIO_SECRET_KEY:trade123}
  bucket: trade-ai
