server:
  port: 8106
spring:
  application:
    name: quotation-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:192.168.2.128:8848}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.2.128}:3306/trade_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
